<script setup>
import FilterSet from '@/components/FilterSet.vue'
import { setOrdering } from '@/utils/generic';

const main = {
   'orders': [
      {
         order: '167470-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'H00GGA0008267614',
         name: 'Geoff Chim',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Middle',
         picker: 'Benjamin Carrol',
         packer: 'Unknown',
         created: '2022-03-28',
         dor: 'false',
         notes: 'Missing 60 pots. Resend PI:52 PA:0 GA',
      },{
         order: '202-2726031-8844335-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'JD0002219852250515',
         name: 'Anita Dale',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-28',
         dor: 'false',
         notes: 'Bucket damaged, resend bucket. GA',
      },{
         order: '204-5072035-2309919-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008167838',
         name: 'Stacy Player',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Middle',
         picker: 'Adam Ogilvie',
         packer: 'Unknown',
         created: '2022-03-29',
         dor: 'false',
         notes: 'damaged in transit please bubble and box',
      },{
         order: '165820-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'H00GGA0008170544',
         name: 'Paul Durston',
         reason: 'Courier',
         option: 'Lost - no tracking',
         room: 'Cutting',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-29',
         dor: 'false',
         notes: '',
      },{
         order: '1184871-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008227444',
         name: 'Colin Naylor',
         reason: 'Customer',
         option: 'Faulty',
         room: 'Cutting',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-29',
         dor: 'true',
         notes: 'Resend 10 pegs GA',
      },{
         order: '204-1814703-9125126-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008275902',
         name: 'Mrs Rosalind Watt',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-29',
         dor: 'false',
         notes: 'Tub damaged in transit. Resend storage tub GA',
      },{
         order: '165301-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'JD0002219852135514',
         name: 'Alan Punt',
         reason: 'Company',
         option: 'Late Delivery',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-29',
         dor: 'false',
         notes: 'Missing form original order GA',
      },{
         order: '206-0515544-2093948-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'JD0002219852200276',
         name: 'Keith Wright',
         reason: 'Courier',
         option: 'Damaged In Transit (disposed)',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-29',
         dor: 'false',
         notes: 'damaged in transit',
      },{
         order: '166937-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'JD0002219852286609',
         name: 'James Robertson',
         reason: 'Courier',
         option: 'Lost - no tracking',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-29',
         dor: 'false',
         notes: '',
      },{
         order: '1179090-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'JD0002219852076709',
         name: 'ian andrews',
         reason: 'Courier',
         option: 'Delivered Not Recieved',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-29',
         dor: 'false',
         notes: '',
      },{
         order: '167758-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'JD0002219852316780',
         name: 'Peter Lecouteur (Howard S Cooke & Co Ltd)',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-29',
         dor: 'false',
         notes: 'Arrived damaged- resend tub GA',
      },{
         order: '206-8062513-5684332-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008213495',
         name: 'STEPHEN ELLIS',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-29',
         dor: 'false',
         notes: 'Three pots damaged - resend GA',
      },{
         order: '166870-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'JD0002219852250748',
         name: 'Peter Mayo',
         reason: 'Courier',
         option: 'Damaged In Transit (disposed)',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-29',
         dor: 'false',
         notes: 'Damaged in transit - being returned to warehouse GA',
      },{
         order: '204-0612191-1654766-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008047795',
         name: 'John Farrell',
         reason: 'Courier',
         option: 'Damaged In Transit (disposed)',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-29',
         dor: 'false',
         notes: 'Damaged in transit - resend GA',
      },{
         order: '206-2956788-2398727-a',
         source: 'Amazon',
         courier: 'T',
         tracking_id: '1575550038376',
         name: 'Christopher Blair-Myers',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-29',
         dor: 'false',
         notes: 'Sent pallet order of cobbles instead of pebbles. No number stamps on the order GA',
      },{
         order: '1186666-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008297061',
         name: 'L Pryde',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-29',
         dor: 'false',
         notes: 'only sent 4 baskets. send missing 2 baskets PI:5',
      },{
         order: '167187-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'H00GGA0008239261',
         name: 'Meraj Syeda (Bionema Limited)',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-29',
         dor: 'false',
         notes: 'Missing 200 labels- send ASAP GA',
      },{
         order: '166914-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'JD0002219852250939',
         name: 'Trace Newton',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-29',
         dor: 'false',
         notes: 'Storage tub damaged in transit. Send replacement. LABEL - PLEASE DELIVER TO FRONT DOOR',
      },{
         order: '203-1071621-5573145-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008163981',
         name: 'Mrs Samantha Adams',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Middle',
         picker: 'Adam Ogilvie',
         packer: 'Unknown',
         created: '2022-03-29',
         dor: 'false',
         notes: 'damaged in transit please bubble/box',
      },{
         order: '1183504-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008177435',
         name: 'William Foskett',
         reason: 'Courier',
         option: 'Lost - no tracking',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-29',
         dor: 'false',
         notes: 'Lost in transit - resend GA',
      },{
         order: '167083-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'JD0002219852256688',
         name: 'ryan lee (dso ltd)',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Salt',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: 'Damaged 10ltr tub - resend storage tub GA',
      },{
         order: 'PS-33540-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'JD0002219852099740',
         name: 'Duncan Morrison',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Salt',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: 'sent bicarb in error - no stamp',
      },{
         order: '1184074-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008198768',
         name: 'Rachel Flowers',
         reason: 'Company',
         option: 'Wrong Size',
         room: 'Cutting',
         picker: 'Morgan Nelson',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: 'sent 1m wide in error - pi47',
      },{
         order: '166969-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'H00GGA0008215172',
         name: 'Kelvin Cheung',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: 'lost 2.5 kg sulphur chips in transit.',
      },{
         order: '1185167-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008239475',
         name: 'david ellis',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: 'Damaged in transit - missing 5 litres',
      },{
         order: '203-5365236-2400304-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008210540',
         name: 'Sandra Jeffrey',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: '1 damaged pot (MB)',
      },{
         order: '204-9674995-6835535-a',
         source: 'Amazon',
         courier: 'HI',
         tracking_id: 'H00GGA0008201072',
         name: 'wilma adams',
         reason: 'Courier',
         option: 'Delivered Not Recieved',
         room: 'Bamboo',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: 'Delivered to the wrong address MB',
      },{
         order: '204-8732253-0952363-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'L11731111000229966',
         name: 'Eloise Barrett',
         reason: 'Courier',
         option: 'Lost - Part Tracking',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: '',
      },{
         order: '168454-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'JJD0002219852377583',
         name: 'Tom Tame (TR Tame & Son)',
         reason: 'Company',
         option: 'Unknown',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: 'Rose Pots not sent with first order. Resend on express. GA',
      },{
         order: '206-6795122-4254724-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'JD0002219852309715',
         name: 'Sarah Partridge',
         reason: 'Courier',
         option: 'Damaged In Transit (disposed)',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: '1 bag damaged in transit (MB)',
      },{
         order: '1186666-b',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008297061',
         name: 'L Pryde',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: '2 missing from order (MB)',
      },{
         order: '206-2956788-2398727-b',
         source: 'Amazon',
         courier: 'T',
         tracking_id: '1575550038376',
         name: 'Christopher Blair-Myers',
         reason: 'Customer',
         option: 'Packing Error',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'true',
         notes: 'Resend. We sent cobbles in stead of pebbles. Resend pebbles. GA',
      },{
         order: '204-7901052-2410748-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008076859',
         name: 'Mr N R Fear',
         reason: 'Courier',
         option: 'Lost - Part Tracking',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: '(MB)',
      },{
         order: '1183406-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008174427',
         name: 'Linzy Kerr',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Bamboo',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: '3 damaged in transit (MB)',
      },{
         order: '166969-b',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'H00GGA0008215172',
         name: 'Kelvin Cheung',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: '(MB)',
      },{
         order: '161000-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'H00GGA0007740124',
         name: 'patricia stephen (phantassie food)',
         reason: 'Other',
         option: 'Faulty',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: '(MB)',
      },{
         order: '1180166-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'JD0002219852112105',
         name: 'Vickie Roper',
         reason: 'Courier',
         option: 'Lost - Part Tracking',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: '(MB)',
      },{
         order: '1185366-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008246367',
         name: 'Kym Fletcher',
         reason: 'Courier',
         option: 'Damaged In Transit (disposed)',
         room: 'Salt',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: '(MB)',
      },{
         order: '230322104259SIMPSON-a',
         source: 'Manual',
         courier: 'W24I',
         tracking_id: 'JD0002219852314027',
         name: 'Kevin J Simpson',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Middle',
         picker: 'Benjamin Carrol',
         packer: 'Josh Dunn',
         created: '2022-03-30',
         dor: 'false',
         notes: 'sent 4" saucers in error pi-52 pa-46',
      },{
         order: '206-1714179-6033902-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'JD0002219852135381',
         name: 'darren harris',
         reason: 'Courier',
         option: 'Lost - no tracking',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: '(MB) 1 bag never arrived',
      },{
         order: '203-1890255-3723537-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008162155',
         name: 'Nicola shaw',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: '(MB)',
      },{
         order: '167977-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'H00GGA0008309931',
         name: 'Anne Grabaskey',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-30',
         dor: 'false',
         notes: 'Bubble and box to prevent damage GA',
      },{
         order: '204-0661642-3453955-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'JD0002219852181128',
         name: 'Mrs M Dawson',
         reason: 'Courier',
         option: 'Damaged In Transit (disposed)',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: '',
      },{
         order: '1183061-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'JD0002219852213484',
         name: 'Colin Foster',
         reason: 'Courier',
         option: 'Lost - Part Tracking',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: 'lost in transit',
      },{
         order: '203-2430502-7853105-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008210350',
         name: 'John Edwards',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: 'damaged in transit',
      },{
         order: '205-1490571-3485911-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'L11731111000232342',
         name: 'Miss Susan Hall',
         reason: 'Company',
         option: 'Faulty',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: '',
      },{
         order: '204-5845908-4798719-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008215398',
         name: 'Mrs Nicolette Shelley',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: 'please box and bubble',
      },{
         order: '1182165-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'JD0002219852177439',
         name: 'cathy mcelhinney',
         reason: 'Courier',
         option: 'Lost - no tracking',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: 'One bag lost - resend GA',
      },{
         order: '1184787-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008223573',
         name: 'Emma Oakes',
         reason: 'Courier',
         option: 'Damaged In Transit (disposed)',
         room: 'Salt',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: 'damaged in transit',
      },{
         order: '204-0501044-5170717-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008172269',
         name: 'Mr Attila Bonifart',
         reason: 'Courier',
         option: 'Lost - Part Tracking',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: '(MB)',
      },{
         order: 'TNFRN5-a',
         source: 'Onbuy',
         courier: 'W24I',
         tracking_id: 'H00GGA0008030283',
         name: 'John Farrell',
         reason: 'Courier',
         option: 'Lost - Part Tracking',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: 'LOST IN TRANSIT',
      },{
         order: '204-0664343-0518753-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008242585',
         name: 'David Warren',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: 'sent standard pre loaded tray - no stamp',
      },{
         order: '1182962-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008157318',
         name: 'Nigel Dancer',
         reason: 'Courier',
         option: 'Damaged In Transit Scan (do not use)',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: 'damaged in transit',
      },{
         order: '202-8169059-3851561-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'JD0002219852164268',
         name: 'Mr John Winser',
         reason: 'Courier',
         option: 'Lost - no tracking',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: 'Being returned - resend',
      },{
         order: '205-1809309-7653166-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'JD0002219852228659',
         name: 'Rini Paul',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: '(MB)',
      },{
         order: '167616-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'JJD0002219852336999',
         name: 'Stephen Whitaker',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: 'pi-5 pa-41 missing from original order',
      },{
         order: '1182392-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'L11731111000230679',
         name: 'Eric Odebrecht',
         reason: 'Courier',
         option: 'Lost - Part Tracking',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: '(MB)',
      },{
         order: '203-9630299-3372311-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'JD0002219852076701',
         name: 'Emma Catto',
         reason: 'Courier',
         option: 'Delivered Not Recieved',
         room: 'Salt',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: '(MB)',
      },{
         order: '1179562-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008036552',
         name: 'Rob Lyon',
         reason: 'Courier',
         option: 'Lost - Part Tracking',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: '(MB)',
      },{
         order: 'FW-1205-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008320492',
         name: 'sheila lakin',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Poison',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: 'Packing issue GA',
      },{
         order: '167816-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'JD0002219852321069',
         name: 'Ted Branch',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: 'Send 2kg of Garden Lime to replace lost in transit. GAS',
      },{
         order: '1179041-a',
         source: 'Ebay',
         courier: 'HI',
         tracking_id: 'H00GGA0008018061',
         name: 'Anton Kok',
         reason: 'Courier',
         option: 'Damaged In Transit Scan (do not use)',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: 'Damaged in transit and disposed of by the courier',
      },{
         order: '202-3193653-2913165-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008149537',
         name: 'John Edwards',
         reason: 'Courier',
         option: 'Damaged In Transit (disposed)',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: '(MB)',
      },{
         order: '1187579-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008329008',
         name: 'Anthony Clark',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Fert',
         picker: 'Alex Furness',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: 'missing from order - pi-58',
      },{
         order: '202-1122961-2408349-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'L11731111000232027',
         name: 'DawnTansom',
         reason: 'Company',
         option: 'Wrong Size',
         room: 'Cutting',
         picker: 'Morgan Nelson',
         packer: 'Morgan Nelson',
         created: '2022-03-31',
         dor: 'false',
         notes: 'send 1 x 3 by mistake (MB)',
      },{
         order: '203-3592251-9259541-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'JD0002219852256264',
         name: 'Christine Morrison',
         reason: 'Courier',
         option: 'Lost - Part Tracking',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: '(MB)',
      },{
         order: '164710-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'JD0002219852079512',
         name: 'Julie Rachel Clark',
         reason: 'Courier',
         option: 'Lost - no tracking',
         room: 'Salt',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-03-31',
         dor: 'false',
         notes: 'Lost in transit - resend GA',
      },{
         order: '206-3760740-1309915-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'JD0002219852226470',
         name: 'Ann Harrison',
         reason: 'Courier',
         option: 'Damaged In Transit Scan (do not use)',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-01',
         dor: 'false',
         notes: '(MB)',
      },{
         order: '1186939-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'L11731111000233069',
         name: 'Ryan Carr',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Cutting',
         picker: 'Morgan Nelson',
         packer: 'Unknown',
         created: '2022-04-01',
         dor: 'false',
         notes: 'we sent one 10Ltr ordered 10 x 1Ltrs (MB)',
      },{
         order: '167695-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'H00GGA0008283771',
         name: 'Colin Mackenzie',
         reason: 'Courier',
         option: 'Damaged In Transit Scan (do not use)',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-01',
         dor: 'false',
         notes: 'damaged in transit',
      },{
         order: '203-4500787-3452339-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008226810',
         name: 'Mrs L M Barbour-Murrie',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Salt',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-01',
         dor: 'false',
         notes: '(MB)',
      },{
         order: '165882-1-a',
         source: 'Manual',
         courier: 'W24I',
         tracking_id: 'H00GGA0008142242',
         name: 'eric fuell (eric fuell)',
         reason: 'Courier',
         option: 'Lost - Part Tracking',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-01',
         dor: 'false',
         notes: '(mb)',
      },{
         order: '1186823-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008303547',
         name: 'Peter Frade',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-01',
         dor: 'false',
         notes: 'Please bubble and pox to prevent damage. GA',
      },{
         order: '1177787-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'JD0002219852038880',
         name: 'Cassandra Wardle',
         reason: 'Courier',
         option: 'Lost - Part Tracking',
         room: 'Salt',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-01',
         dor: 'false',
         notes: '(MB)',
      },{
         order: '203-8735156-8454706-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008257839',
         name: 'Rowan Mackenzie-Stephenson',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Cutting',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-01',
         dor: 'false',
         notes: '(MB)  Put Epsom slats label on replacement container',
      },{
         order: '1185553-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008253300',
         name: 'Alison Evans',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Middle',
         picker: 'Benjamin Carrol',
         packer: 'Adam Ogilvie',
         created: '2022-04-01',
         dor: 'false',
         notes: '(mb)',
      },{
         order: '026-3311823-0515556-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'JD0002219852170620',
         name: 'Peter David White',
         reason: 'Courier',
         option: 'Damaged In Transit Scan (do not use)',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-01',
         dor: 'false',
         notes: '(MB)',
      },{
         order: '167764-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'JD0002219852319449',
         name: 'Geoff Willis (GE SM Willis)',
         reason: 'Courier',
         option: 'Damaged In Transit Scan (do not use)',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-01',
         dor: 'false',
         notes: '(MB)',
      },{
         order: '168372-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'JD0002219852360496',
         name: 'Chris Hepworth',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-01',
         dor: 'false',
         notes: 'Sent westland lawn sand in error. Resend correct product PI:PA 10   GA',
      },{
         order: '1184350-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'JD0002219852250920',
         name: 'Andrea Doyle',
         reason: 'Courier',
         option: 'Address Query',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-03',
         dor: 'false',
         notes: '',
      },{
         order: '1187298-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008320618',
         name: 'james jennings',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-03',
         dor: 'false',
         notes: 'damaged in transit',
      },{
         order: '1185312-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008244616',
         name: 'Mohammed Basharat',
         reason: 'Courier',
         option: 'Lost - Part Tracking',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-03',
         dor: 'false',
         notes: 'lost in transit',
      },{
         order: '1186466-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'JD0002219852324513',
         name: 'paige dwyer',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Salt',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-04',
         dor: 'false',
         notes: 'Send one bag of epsom in stead of bicarb. Resend 1 x 25kg bicarb GA',
      },{
         order: '1182406-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008134803',
         name: 'Charlotte McCormack',
         reason: 'Courier',
         option: 'Lost - Part Tracking',
         room: 'Salt',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-03',
         dor: 'false',
         notes: 'lost in transit',
      },{
         order: '202-0626274-8672322-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008332067',
         name: 'Mrs Paula Blance',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-03',
         dor: 'false',
         notes: 'damaged in transit',
      },{
         order: '1187965-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008341612',
         name: 'Huong Kelly',
         reason: 'Courier',
         option: 'Damaged In Transit Scan (do not use)',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-03',
         dor: 'false',
         notes: 'damaged in transit',
      },{
         order: '1187423-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008325769',
         name: 'patricia moore',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-03',
         dor: 'false',
         notes: '2 x 1ltr tubs missing',
      },{
         order: '167504-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'H00GGA0008268820',
         name: 'GRAEME MARSHALL',
         reason: 'Courier',
         option: 'Damaged',
         room: 'Cutting',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-04',
         dor: 'false',
         notes: '',
      },{
         order: '163703-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'JD0002219852024583',
         name: 'paul coumis',
         reason: 'Other',
         option: 'Not Satisfied',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-04',
         dor: 'false',
         notes: '',
      },{
         order: '026-8349915-1517142-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008159982',
         name: 'Ben Harvey',
         reason: 'Courier',
         option: 'Lost - Part Tracking',
         room: 'Gallup',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-04',
         dor: 'false',
         notes: '',
      },{
         order: '204-4683324-0289165-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008222381',
         name: 'Anne Lyndon',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-04',
         dor: 'false',
         notes: 'Bubble and box to prevent damage GA',
      },{
         order: '1170085-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0007698111',
         name: 'L Whitfield',
         reason: 'Courier',
         option: 'Three Delivery Attempts',
         room: 'Salt',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-04',
         dor: 'false',
         notes: '',
      },{
         order: '026-9749698-7679536-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008275938',
         name: 'Kyle Smith',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Middle',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-04',
         dor: 'false',
         notes: 'Arrived damaged',
      },{
         order: '1186339-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'H00GGA0008285016',
         name: 'Emma Luka',
         reason: 'Courier',
         option: 'Damaged In Transit Scan (do not use)',
         room: 'Salt',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-04',
         dor: 'false',
         notes: 'Damaged in transit',
      },{
         order: '1189585-a',
         source: 'Ebay',
         courier: 'W24I',
         tracking_id: 'JJD0002219852416826',
         name: 'Karolina Kinowska',
         reason: 'Courier',
         option: 'Arrived Damaged',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-04',
         dor: 'false',
         notes: 'damaged in transit',
      },{
         order: '205-3042224-1593150-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0008205385',
         name: 'Alison Forster',
         reason: 'Courier',
         option: 'Lost - Part Tracking',
         room: 'Gallup',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-04',
         dor: 'false',
         notes: 'lost in transit',
      },{
         order: '166910-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'JD0002219852250930',
         name: 'Stuart Steel',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Cutting',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-04',
         dor: 'false',
         notes: 'Sent 10mm bubble in error. PI:PA 0   GA',
      },{
         order: '168680-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'H00GGA0008387480',
         name: 'Alex Wilson (Steepholding)',
         reason: 'Company',
         option: 'Packing Error',
         room: 'Bamboo',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-04',
         dor: 'false',
         notes: 'sent 3ft in error - no stamp',
      },{
         order: '168217-a',
         source: 'Website',
         courier: 'W24I',
         tracking_id: 'JD0002219852360146',
         name: 'Martin Fox',
         reason: 'Courier',
         option: 'Damaged In Transit (disposed)',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-04',
         dor: 'false',
         notes: 'Resend green leaf and tom booster as damaged in transit. Protect well GA',
      },{
         order: '206-4027034-4653130-a',
         source: 'Amazon',
         courier: 'W24I',
         tracking_id: 'H00GGA0007668675',
         name: 'Severine REMISE',
         reason: 'Courier',
         option: 'Lost - Part Tracking',
         room: 'Fert',
         picker: 'Unknown',
         packer: 'Unknown',
         created: '2022-04-04',
         dor: 'false',
         notes: 'Lost in transit',
      }
   ]
}
</script>

<template>
   <el-container>
      <el-header height="65px">
         <filter-set
            :filterSets="[
               'courier',
               'reason',
               'option',
               'room',
               'picker',
               'packer',
            ]"
         />
      </el-header>

      <el-main>
         <el-table
            :data="main.orders"
            style="width: 100%"
            stripe
            @sort-change="setOrdering"
         >
            <el-table-column prop="order" label="Order" width="200" />
            <el-table-column prop="source" label="Source" width="100" />
            <el-table-column prop="courier" label="Courier" width="75" />
            <el-table-column prop="tracking_id" label="Tracking" width="175" />
            <el-table-column prop="name" label="Name" width="125" show-overflow-tooltip />
            <el-table-column prop="reason" label="Reason" width="150" />
            <el-table-column prop="option" label="Option" width="200" show-overflow-tooltip />
            <el-table-column prop="room" label="Room" width="75" />
            <el-table-column prop="picker" label="Picker" width="150" />
            <el-table-column prop="packer" label="Packer" width="150" />
            <el-table-column prop="created" label="Created" width="100" sortable="custom" />
            <el-table-column prop="dor" label="Dor" width="75" sortable="custom" />
            <el-table-column prop="notes" label="Notes" width="200" show-overflow-tooltip />
         </el-table>
      </el-main>
   </el-container>
</template>

<style scoped>
.el-header {
   padding: 1rem;
}
</style>
